name: dotnet coverage

on:
  push:
    paths: "**.cs"
  
  pull_request:
    branches: [ "dev", "main" ]
    paths: "**.cs"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - run: dotnet new console --framework net6.0 -n "SpaceGame" -o "src"
    - run: dotnet new xunit -n SpaceGame.Tests -o test
    - run: dotnet add .\test\SpaceGame.Tests.csproj reference .\src\SpaceGame.csproj
    - run: dotnet add .\test\SpaceGame.Tests.csproj package coverlet.msbuild

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info .\test
    
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info .\test
    
    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: ./coverage/lcov.info